### ISSUE TITLE
EQ Notice for ship02 only?

### ISSUE THREAD

**Issue by takaizu91** [cyberkitsune/PSO2Proxy#170]
Hi, I need some help with my pso2proxy setup. It's not an issue but a query

Can I set EQ_Notice to point other ship eq notice (eg. ship09) because sometimes other ship have different EQ time.

Thanks in advance

**Comment by alama** [comment]
There is only one public source for EQs from PSO2 EQ and it is for Ship 02

**Comment by alama** [comment]
Flyergo's EQ_Notice2 plugin may do for you:
https://github.com/flyergo/PSO2Proxy/blob/master/proxy/plugins/disabled/EQ_Notice2.py

**Comment by takaizu91** [comment]
I see.. I'll give it a try but since pso2 is on maintenance, I'll report back later

**Comment by flyergo** [comment]
Sure you can use it if you want. It works a bit different from the original EQ_Notice, since my plugin always shows ALL ships. (For those who want to switch ships for EQs)

I simply use the public EQ data from a japanese twitter feed (https://twitter.com/pso2_emg_hour) translate it and return it via webservice (http://pso2emq.flyergo.eu/api/v2/) so I can use it for the website (http://pso2emq.flyergo.eu), too.

And the result looks like this:
![eq_notice2](https://cloud.githubusercontent.com/assets/10029199/10347187/0985b4d0-6d33-11e5-9578-42e7c58779c2.png)

Feel free to ask me if you have any trouble setting it up or questions about it.

**Comment by takaizu91** [comment]
Thanks flyergo for the permission. I already test your plugin and find this useful but it would be nice just to show a single ship EQ because me and my team mates happens to be in one ship only so other ships is unnecessary.

It would be nice if you could teach me on how to create webservice for this eq.

**Comment by flyergo** [comment]
No problem. Everyone is free to use it.

Because of how it works currently it only shows everything, but if you want you can build a own webserver in whatever language suits you and parse it so it only shows the things you want to see or even use a different source.

The only thing that might be a bit tricky with my source are scheduled EQs, cause they come in a different format. Either for all ships or only Ship1-5 and 6-10.

But I think about this feature maybe for a future version.

PS: Issue can be closed.
