### ISSUE TITLE
EQ notification

### ISSUE THREAD

**Issue by YielShelion** [cyberkitsune/PSO2Proxy#194]
First of all I have to say sorry for posting this as an issue

I have modified the EQ_notice plugin for my server and integrated it telegram bot to it so it also send EQ notification to the bot subscriber which would be sent to all bot subscriber.

I tried to share my contribution to the community so they can use it as well and I think everyone will be happy for it.

However I am accused for not asking for permission to use bandwidth from ACF server (which is used by all unmodified PSO2Proxy).

I am merely relaying information generated by the plugin, which its behavior is not changed in any way.

So... Do I really have to ask for permission for this? I mean, this is open source and it is in the code afterall

**Comment by cyberkitsune** [comment]
I'm unsure of what @acffordyce973 licences his data under. I will check with him for clarification.
Otherwise, the telegram bot sounds neat! If it's a modification of the EQ notice plugin it'd be cook if you forked pso2proxy and uploaded your changes into your own repo / branch (feel free to remove any telegram API keys from the python script if they are hardcoded.)

**Comment by YielShelion** [comment]
Thanks for the quick reply!

I have also modified globalchat to 3 way chat telegram-pso2-irc but it is not fully completed yet (I don't use IRC so I haven't tested it yet) but telegram-pso2 is fully functional now.
I am really new in github and python coding so I think I would need help forking my code to the repository because it is really hardcoded and I don't understand most of your codes too.

Hoping a reply from acf soon.

**Comment by YielShelion** [comment]
Didn't mean to press that button.

**Comment by TheCrimsonDevil** [comment]
Just to clarify - Who accused you of not asking for permission to use ACF's
server?

**Comment by YielShelion** [comment]
Sirius-91

http://www.pso-world.com/forums/showthread.php?236304-Telegram-Bot-EQ-notification-in-your-phone!

**Comment by acffordyce973** [comment]
The data is made available for both PSO2Proxy and PSO2 Alert users. These I don't mind because both are open source and I am able to see exactly what they are asking from my server in their request. I do agree with Sirius in that if you are modifying the use of the data away from PSO2 Proxy into a standalone bot it is polite to ask for permission. The data was made available to show notifications to in-game, IRC and Windows PSO2 Alert users. I also agree with @CyberKitsune and say that it would indeed be nice if the plugin was forked into the public.

As Sirius said, I do not mind people using the data, but I also actively check what is using it and each time find open source projects behind each request. It would be nice if people did ask, but as long as it's simply one server doing the requests and not a every user that connects to the bot on Telegram (never used this before so I'm not sure how it works) then it's fine. If this helps people playing PSO2 then the data has served its purpose.

**Comment by YielShelion** [comment]
Thanks for the full clarification.

1. The bot is not standalone, it is merged with the plugins itslef
2. I will try to make it publicly available later time
3. It is only one server. With one request per minute. No worry, I keep an eye on the resource usage!

Thanks again, this should clear everythings up now.

**Comment by YielShelion** [comment]
Okay, @acffordyce973, May I ask your permission to use your server's resource? I would be using only one request per minute as the EQ request was not modified.

**Comment by acffordyce973** [comment]
Yes, feel free to use it for as you stated.

**Comment by YielShelion** [comment]
Thanks a lot!
